name: ecos_control
description: A hand controller for the ECoS station

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  shared_preferences: '>=0.5.8 <2.0.0'
  provider: ^4.3.1
  enum_to_string: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # TODO: remove (Temporary)
  assets:
    - assets/images/
